### ISSUE TITLE
Anonymous user flows error

### ISSUE THREAD

**Issue by oleksii-dmytrenko** [angelika-mamchych/BudgetBuddy#35]
As an anonymous when I open flows page I get server error.

Steps to reproduce:
1. Open new private tab/window or a fresh browser
2. go to flows page http://bb.oleksii.org/flows

<img width="614" alt="image" src="https://user-images.githubusercontent.com/1792765/46863805-094bb800-ce21-11e8-83c9-9f194009cd24.png">

**Comment by angelika-mamchych** [comment]
Can't reproduce, probably fixed.
